"""
schemas.py

Pydantic v2 request / response schemas for the MyTadika AI Health Microservice.

All validation mirrors the ranges defined in plan.md §1.2 (Data Quality Audit):
  - age_months : 0 – 72   (children 0–6 years)
  - weight_kg  : 2.5 – 30 kg
  - height_cm  : 45 – 130 cm
  - muac_cm    : 10 – 22 cm   (MUAC = Mid-Upper Arm Circumference)
  - bmi        : 10 – 25
"""

from __future__ import annotations

from typing import Optional
from pydantic import BaseModel, Field, field_validator


# ─────────────────────────────────────────────
#  REQUEST
# ─────────────────────────────────────────────

class PredictionRequest(BaseModel):
    """
    Raw child anthropometric measurements sent by Spring Boot.
    Spring Boot's HealthController validates via Bean Validation first;
    FastAPI validates again here as a second layer.
    """

    child_id:    str   = Field(..., description="Unique child identifier")
    age_months:  float = Field(..., ge=0,   le=72,  description="Age in months (0–72)")
    weight_kg:   float = Field(..., ge=2.5, le=30,  description="Weight in kilograms")
    height_cm:   float = Field(..., ge=45,  le=130, description="Height in centimetres")
    muac_cm:     Optional[float] = Field(None, ge=10, le=22,
                                         description="Mid-upper arm circumference (cm)")
    bmi:         Optional[float] = Field(None, ge=10, le=25,
                                         description="BMI (computed server-side if absent)")
    gender:      Optional[str]   = Field(None, description="'male' or 'female'")

    @field_validator("gender")
    @classmethod
    def gender_must_be_valid(cls, v: Optional[str]) -> Optional[str]:
        if v is not None and v.lower() not in {"male", "female"}:
            raise ValueError("gender must be 'male' or 'female'")
        return v.lower() if v else v


# ─────────────────────────────────────────────
#  RESPONSE
# ─────────────────────────────────────────────

class ProbabilityBreakdown(BaseModel):
    normal:   float
    moderate: float
    severe:   float


class ClinicalFlags(BaseModel):
    is_sam:     bool = Field(False, description="Severe Acute Malnutrition flag")
    is_stunted: bool = Field(False, description="Height-for-age z < -2")
    is_wasted:  bool = Field(False, description="Weight-for-height z < -2")


class PredictionResponse(BaseModel):
    """
    Returned to Spring Boot after ML inference.
    Spring Boot's HealthAdviceService uses `status` + `confidence` + `flags`
    to generate personalised advice via the Java-ported rules engine.
    """

    child_id:        str
    status:          str   = Field(..., description="'normal' | 'moderate' | 'severe'")
    encoded:         int   = Field(..., description="0=normal, 1=moderate, 2=severe")
    confidence:      float = Field(..., ge=0.0, le=1.0)
    probabilities:   ProbabilityBreakdown
    flags:           ClinicalFlags
    model_version:   str
    disclaimer: str = (
        "This prediction is generated by an ML model trained on paediatric "
        "anthropometric data. It does not constitute a medical diagnosis. "
        "Always consult a qualified healthcare professional."
    )


# ─────────────────────────────────────────────
#  HEALTH CHECK
# ─────────────────────────────────────────────

class HealthCheckResponse(BaseModel):
    status:        str
    model_loaded:  bool
    model_version: str
    features:      list[str]
